[package]
name = "bevy_mod_kira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bevy = "0.10.0"
kira = "0.7.1"
bevy_egui = "0.20.1"
egui_extras = "0.21.0"
